### ISSUE TITLE
`service.sh` fails to detect Lawnchair launcher

### ISSUE THREAD

**Issue by tgw314** [reveny/Android-VBMeta-Fixer#1]
The script fails to detect Lawnchair as a launcher because `grep -q "launcher"` doesn't match the Lawnchair process name:
```
$ dumpsys window | grep -E "mCurrentFocus"
  mCurrentFocus=Window{1bbae18 u0 app.lawnchair/app.lawnchair.LawnchairLauncher}
$ dumpsys window | grep -E "mCurrentFocus" | grep "launcher"
$
```
https://github.com/reveny/Android-VBMeta-Fixer/blob/b3b443d22a2917462c3c688aa9e0269773806d0e/module/service.sh#L8-L16

The script enters an infinite loop because the launcher detection condition is never met.

**Comment by tgw314** [comment]
To use regular expressions with grep, the `-E` option is required.
```sh
grep -qE "launcher|lawnchair"
```

**Comment by reveny** [comment]
> To use regular expressions with grep, the `-E` option is required.
> 
> ```shell
> grep -qE "launcher|lawnchair"
> ```

Fixed, thank you.
