### ISSUE TITLE
Digest is null, device integrity breaks

### ISSUE THREAD

**Issue by Searinox** [reveny/Android-VBMeta-Fixer#3]
Magisk 28 + LSposed 1.10 + Tricky Store 1.2.0 + PIFork 11 + Shamiko 1.1.1 + Zygisk-Assistant 2.1.3 @ LineageOS 20.

Without this module: abnormal boot, vbmeta digest empty. Passes basic & device integrity.

With it: abnormal boot, vbmeta digest is null. Only passes basic integrity.

Meanwhile it reports status: active in the modules list.

Also, removing the module leaves behind com.reveny.vbmetafix.service app installed on the device even after restart.

Attempted again with ZygiskNext 1.2.4 instead of relying on Magisk's implementation. Same result.

**Comment by reveny** [comment]
What is the result of 
`dumpsys window | grep -E "mCurrentFocus"`
When ran in adb and the phone is on the home screen?

**Comment by Searinox** [comment]
Although I wasn't able to do that I did get a callstack for the service:

**Comment by Searinox** [comment]
I found out why the integrity breaks in the meantime: I can get up to and including strong integrity with a blank(empty) digest. It's reported as abnormal by root detectors but the integrity checks pass. It's either a blank string to pass or manually setting in the correct hash which makes the error go away entirely without affecting integrity.

From what I can see there's exception handling in this module to always return the "null" string if something goes wrong. Setting the digest to "null" breaks the integrity. Maybe at least leave it empty?

**Comment by reveny** [comment]
> Update:
> 
> I edited service.sh to this: https://pastebin.com/DPRaTBRp
> 
> And now everything passes!
> 
> Here's the odd bit: I set up separate messages for getting and failing to acquire the hash to a very specific text and that's not what I'm seeing in the module description. I'm seeing the standard message ($boilerplate). This tells me that it was NOT my null handler that fixed it but rather the counter, which I increased from 5 to 15. Perhaps 5 was just too little for some systems?

Implemented the changes, thank you for the help!
